import images from "./images"
import galleryImages from "./galleryImages"

export default [
    {
        id: 1,
         flavor: 'SOUR PATCH Kids Redberry',
          price: 29.76,
          image: images.canRed,
          paramId: 'redberry',
          gallery1: galleryImages.redberry1,
          gallery2: galleryImages.redberry2,
          gallery3: galleryImages.redberry3,
        },
    {
        id: 2,
         flavor: 'Citrus',
          price: 29.76,
        image: images.canCitrus,
        paramId: 'citrus',
        gallery1: galleryImages.citrus1,
        gallery2: galleryImages.citrus2,
        gallery3: galleryImages.citrus3,
    },
    {
        id: 3,
         flavor: 'Orange Cream',
          price: 29.76,
        image: images.canOrange,
        paramId: 'orange-cream',
        gallery1: galleryImages.orange1,
        gallery2: galleryImages.orange2,
        gallery3: galleryImages.orange3,},
    {
        id: 4,
         flavor: 'FAZE Pop',
          price: 29.99,
        image: images.canFaze,
        paramId: 'faze-pop',
        gallery1: galleryImages.faze1,
        gallery2: galleryImages.faze2,
        gallery3: galleryImages.faze3,},
    {
        id: 5,
         flavor: 'Cherry Limeade',
          price: 29.99,
        image: images.canCherry,
        paramId: 'cherry-limeade',
        gallery1: galleryImages.cherrylime1,
        gallery2: galleryImages.cherrylime2,
        gallery3: galleryImages.cherrylime3,},
    {
        id: 6,
        flavor: 'SOUR PATCH Kids Blue Raspberry',
        price: 29.76,
        image: images.canBlue,
        paramId: 'blue-raspberry',
        gallery1: galleryImages.blue1,
        gallery2: galleryImages.blue2,
        gallery3: galleryImages.blue3,},
    {
        id: 7,
         flavor: 'SWEDISH FISH',
        price: 29.99,
        image: images.canSwedish,
        paramId: 'swedish-fish',
        gallery1: galleryImages.swedish1,
        gallery2: galleryImages.swedish2,
        gallery3: galleryImages.swedish3,},
    {
        id: 8,
         flavor: 'Tropical Mango',
        price: 29.88,
        image: images.canMango,
        paramId: 'tropical-mango',
        gallery1: galleryImages.mango1,
        gallery2: galleryImages.mango2,
        gallery3: galleryImages.mango3,},
    {
        id: 9,
         flavor: 'WARHEADS Sour Green Apple',
        price: 29.76,
        image: images.canSga,
        paramId: 'sour-green-apple',
        gallery1: galleryImages.sga1,
        gallery2: galleryImages.sga2,
        gallery3: galleryImages.sga3,},
    {
        id: 10,
         flavor: 'WARHEADS Sour Watermelon',
        price: 29.76,
        image: images.canWar,
        paramId: 'sour-watermelon',
        gallery1: galleryImages.sw1,
        gallery2: galleryImages.sw2,
        gallery3: galleryImages.sw3,}
]